import SwiftUI

struct GitHubProfile: Decodable { let login: String; let name: String?; let avatarURL: URL; let htmlURL: URL
    enum CodingKeys: String, CodingKey { case login, name; case avatarURL = "avatar_url"; case htmlURL = "html_url" }
}
@MainActor final class GitHubAuthor: ObservableObject {
    @Published var profile = GitHubProfile(login: "tinysweetUwU", name: "tinysweet", avatarURL: URL(string: "https://avatars.githubusercontent.com/u/110331292?v=4")!, htmlURL: URL(string: "https://github.com/tinysweetUwU")!)
    init() { Task { if let url = URL(string: "https://api.github.com/users/tinysweetUwU") { var req = URLRequest(url: url); req.setValue("BCEditor", forHTTPHeaderField: "User-Agent"); if let (data, _) = try? await URLSession.shared.data(for: req), let profile = try? JSONDecoder().decode(GitHubProfile.self, from: data) { self.profile = profile } } } }
}

struct EditorTool: Identifiable, Hashable { let id = UUID(); let title: String; let icon: String; let color: Color; let features: [String] }

struct ToolsView: View {
    private let tools = [
        EditorTool(title: "Items", icon: "shippingbox.fill", color: .orange, features: ["Cat Food", "XP", "Tickets", "NP / Leadership", "Catfruit / Catseyes / Catamins", "Battle Items"]),
        EditorTool(title: "Cats & Skills", icon: "pawprint.fill", color: .pink, features: ["Cat ID / level", "Unlock and max forms", "Talents", "Cat Storage"]),
        EditorTool(title: "Enemy Guide", icon: "bug.fill", color: .brown, features: ["Unlock all enemy entries", "Clear enemy entries"]),
        EditorTool(title: "Levels", icon: "map.fill", color: .indigo, features: ["Aku Realm", "All available stages"]),
        EditorTool(title: "Gamatoto", icon: "hammer.fill", color: .teal, features: ["XP / expedition", "Ototo cannons"]),
        EditorTool(title: "Account", icon: "person.crop.circle.fill", color: .blue, features: ["Equipment menu", "Gold Pass reset"]),
        EditorTool(title: "Gatya & Other", icon: "sparkles", color: .purple, features: ["Gatya seeds", "Missions", "Medals"]),
        EditorTool(title: "Fixes", icon: "wrench.and.screwdriver.fill", color: .red, features: ["Gamatoto", "Ototo", "Time errors"])
    ]
    var body: some View { NavigationStack { ScrollView { LazyVStack(spacing: 14) { ForEach(tools) { tool in NavigationLink { ToolDetail(tool: tool) } label: { ToolTile(tool: tool) } } }.padding() }.navigationTitle("Tools") } }
}
struct ToolTile: View { let tool: EditorTool; var body: some View { HStack(spacing: 14) { Image(systemName: tool.icon).font(.title2).foregroundStyle(.white).frame(width: 48, height: 48).background(tool.color.gradient, in: RoundedRectangle(cornerRadius: 13)); VStack(alignment: .leading) { Text(tool.title).font(.headline); Text("\(tool.features.count) editors").font(.caption).foregroundStyle(.secondary) }; Spacer(); Image(systemName: "chevron.right").foregroundStyle(.tertiary) }.padding().frame(maxWidth: .infinity).background(.background, in: RoundedRectangle(cornerRadius: 18)).shadow(color: .black.opacity(0.08), radius: 8, y: 3) } }

struct ToolDetail: View {
    @EnvironmentObject private var store: SaveStore; let tool: EditorTool
    @State private var values: [String: String] = ["catfood":"", "xp":"", "normal_tickets":"", "rare_tickets":"", "platinum_tickets":"", "legend_tickets":"", "hundred_million_ticket":"", "platinum_shards":"", "np":"", "leadership":"", "rare_seed":"", "normal_seed":"", "event_seed":""]
    @State private var catID = "0"; @State private var catLevel = "1"
    @State private var resourceKind = "0"; @State private var resourceIndex = "0"; @State private var resourceAmount = "0"
    @State private var battleIndex = "0"; @State private var battleAmount = "0"
    @State private var storageSlot = "0"; @State private var storageType = "1"; @State private var storageID = "0"
    @State private var mapID = "0"; @State private var mapStar = "0"; @State private var stageID = "0"
    @State private var ticketKind = "0"; @State private var ticketIndex = "0"; @State private var ticketAmount = "0"
    @State private var helperIndex = "0"; @State private var helperID = "0"; @State private var engineerCount = "0"; @State private var cannonID = "0"; @State private var cannonDevelopment = "3"; @State private var cannonLevel = "10"
    var body: some View { Form {
        if tool.title == "Items" { Section("Direct edit") { field("Cat Food", "catfood"); field("XP", "xp"); field("Normal Tickets", "normal_tickets"); field("Rare Tickets", "rare_tickets"); field("Platinum Tickets", "platinum_tickets"); field("Legend Tickets", "legend_tickets"); field("100M Tickets", "hundred_million_ticket"); field("Platinum Shards", "platinum_shards"); field("NP", "np"); field("Leadership", "leadership"); TextField("Resource type (0 fruit / 1 eyes / 2 catamins)", text: $resourceKind).keyboardType(.numberPad); TextField("Resource index", text: $resourceIndex).keyboardType(.numberPad); TextField("Resource amount", text: $resourceAmount).keyboardType(.numberPad); Button("Apply resource", systemImage: "leaf.fill") { applyResource() }.disabled(!store.hasSave); TextField("Battle item index", text: $battleIndex).keyboardType(.numberPad); TextField("Battle item amount", text: $battleAmount).keyboardType(.numberPad); Button("Apply battle item", systemImage: "shield.fill") { applyBattleItem() }.disabled(!store.hasSave); action("Max basic items", "max_items", "arrow.up.to.line"); action("Max resources", "max_resources", "leaf.fill"); action("Max misc resources", "max_misc_resources", "shippingbox.fill"); action("Max battle items", "max_battle_items", "shield.fill") } }
        if tool.title == "Cats & Skills" { Section("Direct edit") { TextField("Cat ID", text: $catID).keyboardType(.numberPad); TextField("Base level", text: $catLevel).keyboardType(.numberPad); Button("Apply cat level", systemImage: "pencil") { if let id = Int(catID), let level = Int(catLevel) { store.applyNativeAction("set_cat_level", value: (id << 16) | level) } }.disabled(!store.hasSave); TextField("Storage slot", text: $storageSlot).keyboardType(.numberPad); TextField("Storage type (1 cat / 2 skill / 3 item)", text: $storageType).keyboardType(.numberPad); TextField("Storage ID", text: $storageID).keyboardType(.numberPad); Button("Apply storage item", systemImage: "tray.and.arrow.down.fill") { applyStorage() }.disabled(!store.hasSave); action("Unlock all cats", "unlock_all_cats", "lock.open.fill"); action("Max cats and forms", "max_cats", "star.fill"); action("Max talents", "max_talents", "sparkles"); action("Max special skills", "max_special_skills", "bolt.fill"); action("Unlock Cat Guide", "unlock_cat_guide", "book.fill"); action("Fill Cat Storage", "fill_cat_storage", "tray.full.fill"); action("Clear Cat Storage", "clear_cat_storage", "trash") } }
        if tool.title == "Enemy Guide" { Section("Direct edit") { action("Unlock all enemy entries", "unlock_enemy_guide", "lock.open.fill"); action("Clear enemy entries", "clear_enemy_guide", "trash") } }
        if tool.title == "Levels" { Section("Direct edit") { TextField("Story map", text: $mapID).keyboardType(.numberPad); TextField("Star", text: $mapStar).keyboardType(.numberPad); TextField("Stage", text: $stageID).keyboardType(.numberPad); Button("Clear story stage", systemImage: "checkmark.circle.fill") { if let m = Int(mapID), let s = Int(mapStar), let st = Int(stageID) { store.applyNativeAction("clear_story_stage", value: m | (s << 8) | (st << 16)) } }.disabled(!store.hasSave); action("Unlock Aku Realm", "unlock_aku_realm", "lock.open.fill"); action("Clear available stages", "clear_all_maps", "map.fill"); action("Allow Filibuster replay", "allow_filibuster", "repeat.circle") } }
        if tool.title == "Gamatoto" { Section("Direct edit") { TextField("Helper slot", text: $helperIndex).keyboardType(.numberPad); TextField("Helper ID", text: $helperID).keyboardType(.numberPad); Button("Apply helper", systemImage: "person.fill") { if let i = Int(helperIndex), let id = Int(helperID) { store.applyNativeAction("set_gamatoto_helper", value: i | (id << 16)) } }.disabled(!store.hasSave); TextField("Ototo engineers", text: $engineerCount).keyboardType(.numberPad); Button("Apply engineers", systemImage: "person.3.fill") { if let n = Int(engineerCount) { store.applyNativeAction("set_ototo_engineers", value: n) } }.disabled(!store.hasSave); TextField("Cannon ID", text: $cannonID).keyboardType(.numberPad); TextField("Development (0-3)", text: $cannonDevelopment).keyboardType(.numberPad); TextField("Part level", text: $cannonLevel).keyboardType(.numberPad); Button("Apply cannon", systemImage: "bolt.fill") { if let id = Int(cannonID), let d = Int(cannonDevelopment), let l = Int(cannonLevel) { store.applyNativeAction("set_ototo_cannon", value: id | (d << 8) | (l << 16)) } }.disabled(!store.hasSave); action("Max Gamatoto XP", "max_gamatoto", "hammer.fill"); action("Max Gamatoto materials", "max_gamatoto_materials", "shippingbox.fill"); action("Max Cat Shrine", "max_cat_shrine", "sparkles"); action("Max Ototo cannons", "max_ototo_cannons", "bolt.fill") } }
        if tool.title == "Account" { Section("Direct edit") { action("Unlock equipment menu", "unlock_equip_menu", "lock.open.fill"); action("Reset Gold Pass", "reset_officer_pass", "arrow.counterclockwise"); action("Enable restart pack", "set_restart_pack", "gift.fill"); action("Clear tutorial progress", "clear_tutorial", "flag.checkered") } }
        if tool.title == "Gatya & Other" { Section("Direct edit") { field("Rare Gatya Seed", "rare_seed"); field("Normal Gatya Seed", "normal_seed"); field("Event Gatya Seed", "event_seed"); TextField("Ticket type (0 event / 1 lucky / 2 event-2)", text: $ticketKind).keyboardType(.numberPad); TextField("Ticket index", text: $ticketIndex).keyboardType(.numberPad); TextField("Ticket amount", text: $ticketAmount).keyboardType(.numberPad); Button("Apply event ticket", systemImage: "ticket.fill") { applyEventTicket() }.disabled(!store.hasSave); action("Complete missions", "complete_missions", "checkmark.seal.fill"); action("Unlock medals", "unlock_medals", "rosette") } }
        if tool.title == "Fixes" { Section("Direct fixes") { action("Fix Gamatoto", "fix_gamatoto_crash", "wrench.and.screwdriver"); action("Fix Ototo", "fix_ototo_crash", "hammer.fill"); action("Fix time errors", "fix_time_errors", "clock.arrow.2.circlepath"); action("Reset golden cat CPUs", "reset_golden_cpus", "cpu") } }
        Section("Features") { ForEach(tool.features, id: \.self) { Label($0, systemImage: "checkmark.circle") } }
    }.navigationTitle(tool.title).onAppear { refresh() }.onChange(of: store.basicValues) { _, _ in refresh() } }
    @ViewBuilder private func field(_ title: String, _ key: String) -> some View { HStack { TextField(title, text: Binding(get: { values[key] ?? "" }, set: { values[key] = $0 })).keyboardType(.numberPad); Button("Apply") { if let value = Int(values[key] ?? "") { store.updateBasicItem(key, value: value) } }.disabled(!store.hasSave || Int(values[key] ?? "") == nil) } }
    private func action(_ title: String, _ key: String, _ icon: String) -> some View { Button(title, systemImage: icon) { store.applyNativeAction(key) }.disabled(!store.hasSave) }
    private func refresh() { if let catFood = store.summary?.catFood { values["catfood"] = String(catFood) }; for key in values.keys { if let value = store.basicValues[key] { values[key] = String(value) } } }
    private func applyResource() { if let kind = Int(resourceKind), let index = Int(resourceIndex), let amount = Int(resourceAmount) { store.applyNativeAction("set_resource", value: kind | (index << 8) | (amount << 16)) } }
    private func applyBattleItem() { if let index = Int(battleIndex), let amount = Int(battleAmount) { store.applyNativeAction("set_battle_item", value: index | (amount << 16)) } }
    private func applyStorage() { if let slot = Int(storageSlot), let type = Int(storageType), let id = Int(storageID) { store.applyNativeAction("set_cat_storage_item", value: slot | (type << 16) | (id << 24)) } }
    private func applyEventTicket() { if let kind = Int(ticketKind), let index = Int(ticketIndex), let amount = Int(ticketAmount) { store.applyNativeAction("set_event_ticket", value: kind | (index << 8) | (amount << 16)) } }
}

struct SettingsView: View { @StateObject private var author = GitHubAuthor(); var body: some View { NavigationStack { List { Section("Application") { LabeledContent("Version", value: "1.0.1") }; Section("Author") { HStack { AsyncImage(url: author.profile.avatarURL) { phase in if let image = phase.image { image.resizable().scaledToFill() } else { Image(systemName: "person.crop.circle.fill").resizable().scaledToFit().foregroundStyle(.secondary) } }.frame(width: 56, height: 56).clipShape(Circle()); VStack(alignment: .leading) { Text(author.profile.name ?? author.profile.login).font(.headline); Text("@\(author.profile.login)").font(.caption).foregroundStyle(.secondary) }; Spacer() }; Link(destination: author.profile.htmlURL) { Label("Open GitHub profile", systemImage: "link") } }; Section("Safety") { Text("A backup is created before every native edit.") } }.navigationTitle("Settings") } } }
